plugins {
    id 'com.android.application'
}

def releasePropertiesFile = rootProject.file("release.properties")
def releaseProperties = new Properties()
if (releasePropertiesFile.exists()) {
    releasePropertiesFile.withInputStream { releaseProperties.load(it) }
}

android {
    namespace "net.openconnect_vpn.android"
    defaultConfig {
        minSdk 23
        targetSdk 34
        compileSdk 35

        versionCode 1130
        versionName "1.13-split"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        if (releasePropertiesFile.exists()) {
            release {
                storeFile rootProject.file(releaseProperties["storeFile"])
                storePassword releaseProperties["storePassword"]
                keyAlias releaseProperties["keyAlias"]
                keyPassword releaseProperties["keyPassword"]
            }
        }
    }
    buildTypes {
        debug {
            applicationIdSuffix ".split"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (releasePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
    lintOptions {
        disable 'ExtraTranslation'
        disable 'IconColors'
        disable 'InconsistentArrays'
        disable 'MissingTranslation'
        disable 'OldTargetApi'
        disable 'SuspiciousIndentation'

        // It's a tremendous amount of work to get rid of all references to `Context` in the app
        disable 'StaticFieldLeak'

        baseline file("lint-baseline.xml")
    }
    buildFeatures {
        aidl true
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            if (variant.buildType.name == "debug") {
                outputFileName = "openconnect-split-debug.apk"
            } else if (variant.buildType.name == "release") {
                outputFileName = "openconnect-split-1.13.apk"
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
